import os

try:
    from zoneinfo import ZoneInfo
except ImportError:
    from backports.zoneinfo import ZoneInfo


MARKET_TZ = ZoneInfo("America/New_York")

# --- ALERT MODES ---
ENABLE_INTRADAY_ALERTS = True
ENABLE_SWING_ALERTS = True

INTRADAY_MIN_SCORE = 85
SWING_MIN_SCORE = 85
SWING_MIN_REASONS = 3
SWING_A_PLUS_SCORE = 85
SWING_A_SCORE = 75
SWING_WATCH_SCORE = 65

SWING_ALERT_COOLDOWN_SEC = 7200

SWING_HOLD_DAYS_MIN = 2
SWING_HOLD_DAYS_MAX = 10
SWING_PULLBACK_TOLERANCE_PCT = 1.0
SWING_ATR_STOP_MULTIPLIER = 1.5
SWING_ATR_TARGET_MULTIPLIER = 4.0
MAX_SWING_ALERTS_PER_SCAN = 3

# --- RISK MANAGEMENT ---
ACCOUNT_SIZE = 100000
RISK_PER_TRADE_PCT = 0.01
MAX_POSITION_PCT = 0.2

BASE_WATCHLIST = [
    "NVDA", "AMD", "AVGO", "TSM", "ARM", "MU", "INTC", "SMCI",
    "AAPL", "MSFT", "AMZN", "META", "GOOGL", "TSLA", "NFLX",
    "PLTR", "SNOW", "CRM", "ORCL", "ADBE", "NOW", "DDOG", "NET",
    "CRWD", "PANW", "MDB", "AI",
    "SNDK", "LITE", "AAOI", "MRVL", "QCOM", "AMAT", "LRCX", "KLAC",
    "ON", "MPWR", "ALAB", "DELL", "HPE",
    "IONQ", "RGTI", "QBTS", "QUBT", "ARQQ",
    "COIN", "MSTR", "MARA", "RIOT", "HOOD", "SOFI", "AFRM", "PYPL",
    "SQ", "UPST", "RIVN", "LCID", "NIO", "XPEV", "LI", "F", "GM",
    "XOM", "CVX", "OXY", "SLB", "USO", "FCX", "CLF", "NEM",
    "LMT", "RTX", "NOC", "BA", "RKLB", "ACHR", "JOBY",
    "COST", "WMT", "HD", "LOW", "NKE", "SBUX", "MCD",
    "UAL", "DAL", "AAL", "CCL", "RCL", "ABNB", "UBER",
    "JPM", "BAC", "WFC", "GS", "MS", "V", "MA", "AXP",
    "LLY", "NVO", "UNH", "VRTX", "MRNA", "BIIB", "REGN", "AXSM",
    "SPY", "QQQ", "IWM", "DIA", "SMH", "SOXX", "ARKK", "TQQQ", "SQQQ"
]

USE_AUTO_WATCHLIST = True
AUTO_WATCHLIST_LIMIT = 40
MIN_AUTO_VOLUME = 2_000_000
MIN_AUTO_CHANGE_PCT = 2.0
MIN_STOCK_PRICE = 8

MARKET_BIAS_TICKERS = ["SPY", "QQQ", "IWM", "SMH"]
MARKET_BIAS_WEIGHT = 15
REQUIRE_MARKET_BIAS = False
MARKET_BIAS_CONFLICT_PENALTY = 8

REQUIRE_PM_OR_PD_BREAK_FOR_A_PLUS = True
A_PLUS_BREAKOUT_BONUS = 20
A_PLUS_BREAKOUT_PENALTY = 35

A_PLUS_MODE = True
A_PLUS_PULLBACK_MIN_SCORE = 85
A_PLUS_BREAKOUT_MIN_SCORE = 80
A_PLUS_MOMENTUM_MIN_SCORE = 85
PULLBACK_ZONE_TOLERANCE_PCT = 0.65
PULLBACK_MIN_CONFIRMATIONS = 3
PULLBACK_MIN_RR = 2.2
PULLBACK_STOP_ATR_MULTIPLIER = 0.8
PULLBACK_TARGET_ATR_MULTIPLIER = 2.5

FIB_FILTER_ENABLED = True
FIB_LEVELS = [0.382, 0.5, 0.618]
FIB_TOLERANCE_PCT = 0.45
FIB_LOOKBACK_SWING_BARS = 20
FIB_CONFLUENCE_ENABLED = True
FIB_CONFLUENCE_TOLERANCE_PCT = 0.55
FIB_MIN_CONFLUENCE_COUNT = 2
FIB_EXTENSION_ENABLED = True
FIB_EXTENSION_LEVELS = [1.272, 1.618]
FIB_EXTENSION_TARGET_PRIORITY = True
MTF_FIB_CONFLUENCE_ENABLED = True
MTF_FIB_TOLERANCE_PCT = 0.65
MTF_FIB_MIN_MATCHES = 1
FIB_ENTRY_ZONE_ENABLED = True
FIB_ENTRY_ZONE_TOLERANCE_PCT = 0.35
FIB_ENTRY_REQUIRE_RECLAIM = True
FIB_ENTRY_MIN_CONFIRMATIONS = 3

HIGH_WIN_RATE_MODE = True
MIN_INTRADAY_REL_VOL_A_PLUS = 1.3
MIN_DAILY_REL_VOL_A_PLUS = 1.0
MIN_AVG_20_VOLUME_A_PLUS = 1_000_000
REQUIRE_ETF_ALIGNMENT_A_PLUS = True
REQUIRE_TREND_ALIGNMENT_A_PLUS = True
ALLOW_NEUTRAL_15M_FOR_BREAKOUT = False

SCAN_INTERVAL_SEC = 300
ALERT_COOLDOWN_SEC = 900

EMA_FAST = 9
EMA_SLOW = 21
EMA_TREND = 50
DMA_SHORT = 20
DMA_FAST = 50
DMA_SLOW = 200
ORB_MINUTES = 15

MIN_CALL_SCORE = 75
MIN_PUT_SCORE = 75
MIN_AI_CONFIDENCE = 75

MAX_EXTENSION_FROM_VWAP_PCT = 2.5
MAX_EXTENSION_FROM_ORB_PCT = 1.5
RETEST_TOLERANCE_PCT = 0.35
MIN_RISK_REWARD = 1.5
REQUIRE_RETEST = True
STRICT_RETEST_IN_CHOP = True

RELATIVE_STRENGTH_WEIGHT = 10
VOLUME_SPIKE_WEIGHT = 10
CONTINUATION_WEIGHT = 10
VOLUME_SPIKE_MULTIPLIER = 1.5

ATR_PERIOD = 14
ATR_STOP_MULTIPLIER = 1.2
ATR_TARGET_MULTIPLIER = 2.2

CONFIRM_5M_15M = True
TIMEFRAME_CONFIRM_WEIGHT = 5

SUPPORT_RESISTANCE_BUFFER_PCT = 0.35
FAILED_BREAKOUT_WEIGHT = 30
SR_REJECTION_WEIGHT = 25

RANK_TOP_ALERTS_ONLY = True
MAX_ALERTS_PER_SCAN = 5

QUALITY_WINDOWS = [
    ("09:30", "12:30"),
    ("14:30", "15:59"),
]

SECTOR_ETF_WEIGHT = 15
REQUIRE_SECTOR_CONFIRMATION = True

ENABLE_REGIME_SCORING = True
CHOP_EXTENSION_MULTIPLIER = 0.75
CHOP_MIN_SCORE_BONUS = 5
TREND_EXTENSION_MULTIPLIER = 1.15

SECTOR_ETF_MAP = {
    "NVDA": "SMH", "AMD": "SMH", "AVGO": "SMH", "MU": "SMH", "SMCI": "SMH",
    "JPM": "XLF", "BAC": "XLF", "GS": "XLF",
    "XOM": "XLE", "CVX": "XLE", "OXY": "XLE",
    "TSLA": "XLY", "AMZN": "XLY",
}

LOG_FILE = "stock_technical_alerts.csv"

POLYGON_API_KEY = os.getenv("POLYGON_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
ALPACA_API_KEY = os.getenv("ALPACA_API_KEY", "")
ALPACA_SECRET_KEY = os.getenv("ALPACA_SECRET_KEY", "")
